version: 2
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: False
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.12
python:
  install:
    - requirements: docs/requirements.txt
