{\rtf1\ansi\ansicpg1252\cocoartf2578
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
package:\
  name: testuqpy\
  version: \{\{ version \}\}\
  \
build:\
  noarch: python\
  number: 0\
\
requirements:\
  host:\
    - python\
    - pip\
  run:\
    - python\
\
#about:\
#  home: https://github.com/SURGroup/UQpy\
#  license: MIT\
#  summary: UQpy is a general purpose Python toolbox for modeling uncertainty in physical and mathematical systems.\
#  doc_url: https://uqpyproject.readthedocs.io}