[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
# Core settings
line-length = 100
target-version = "py39"

[tool.ruff.lint]

#What rules to enable
select = ["E", "F", "I", "B", "S"]
# E = pycodestyle errors
# F = pyflakes
# I = isort (import sorting)
# B = bugbear (best practices)
# UP = pyupgrade (modernization)
# D = pydocstyle (docstring rules)
# S = bandit (security)

#What rules to ignore
ignore = ["E402","E501","E712","E721", "E722", "E731", "E741", "F401", "F403", "F405","F541","F811", "F841","I001", "B007","B008","B009", "B023", "B024", "B027", "S605", "S301", "S307","S101", "S102"]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "lf"
docstring-code-format = true