name: Build and Test

on: 
    push:
        branches:
        - master
        - feature/*
        - bugfix/*
        - dependabot/*
        - dependabot/**
    pull_request:
        branches:
        - master
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    testing:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            group: [1, 2, 3, 4, 5]
        steps:
          - uses: actions/checkout@v4          
          - name: Set up Python 3.9
            uses: actions/setup-python@v5
            with:
              python-version: 3.9
              cache: 'pip'              
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-cov pytest-split hypothesis pytest-rerunfailures
          - name: Run tests with retries
            run: |
                PYTHONPATH=src pytest \
                --durations=10 \
                --splits 5 --group ${{ matrix.group }} \
                --reruns=3  --reruns-delay=10 --maxfail=5 -ra \
                --cov=src tests/ --junitxml=junit/test-results.xml --cov-report= --cov-report=xml --cov-report=html --cov-report=term
          - name: Upload coverage
            uses: actions/upload-artifact@v4
            with:
              name: coverage${{ matrix.group }}
              path: .coverage
              include-hidden-files: true

    coverage:
        needs: testing
        runs-on: ubuntu-latest
        steps: 
          - uses: actions/checkout@v4
          - name: Download all artifacts
            uses: actions/download-artifact@v4
          - name: Show coverage files
            run: ls -R
          - name: Run coverage
            run: |
              mv coverage1/.coverage .coverage.1
              mv coverage2/.coverage .coverage.2
              mv coverage3/.coverage .coverage.3
              mv coverage4/.coverage .coverage.4
              mv coverage5/.coverage .coverage.5
              pip install coverage
              coverage combine .coverage.*
              coverage xml -o coverage.xml
              coverage lcov -o coverage.lcov
          - name: Upload coverage report
            uses: actions/upload-artifact@v4
            with:
              name: coverage-report
              path: coverage.xml

          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v5
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
          
          - name: Upload coverage to Coveralls
            uses: coverallsapp/github-action@v2
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              path-to-lcov: coverage.lcov
