name: Build and Test

on: 
    push:
        branches:
        - master
        - feature/*
        - bugfix/*
    pull_request:
        branches:
        - master

jobs:
    checkout-and-install-dependencies:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.9
          uses: actions/setup-python@v5
          with:
            python-version: 3.9
            cache: 'pip'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
    linting:
        runs-on: ubuntu-latest
        needs: checkout-and-install-dependencies
        steps:
        - name: Install Pylint
          run: pip install pylint
        - name: Lint code
          run: |
            echo ${{ github.workspace }}
            ls ${{ github.workspace }}
            # PYTHONPATH=src pylint --ignored-modules=numpy,scipy,matplotlib,sklearn --disable=E0202,E1136,E1120,E0401,E0213 --disable=R,C,W src/UQpy

    # testing:
    #     runs-on: ubuntu-latest
    #     needs: checkout-and-install-dependencies
    #     steps:
    #     - name: Install pytest dependencies
    #       run: pip install pytest pytest-cov
    #     - name: Run tests
    #       run: PYTHONPATH=src pytest --cov=src tests/ --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
        
    #     - name: Publish test results
    #       if: always()
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: test-results
        
    #     - name: Upload coverage report
    #       if : always()
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: coverage-report
    #         path: junit/test-results.xml