name: Build & Deploy Sphinx Docs

on:
  pull_request:
    branches:
      - master  
      - dependabot/*      
    # paths:
    #   - 'docs/**'
    #   - 'src/**'  # Run only if docs or src changes
  push:
    branches:
      - master  # Deploy to production when merged
    # paths:
    #   - 'docs/**'
    #   - 'src/**'  # Run only if docs or src changes
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write  
  
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
            cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py 1.0.0 develop
          pip install -r docs/requirements.txt
      - name: Make the Sphinx Docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Upload Built Docs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html
          retention-days: 1  # Keep it only for 1 day to avoid unnecessary storage

  deploy-staging:
    needs: build-docs
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Built Docs Artifact
        uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html

      - name: Deploy to GitHub Pages (Staging)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-preview  # Separate branch for previews
          publish_dir: docs/build/html
          keep_files: false  # Overwrite previous previews
          force_orphan: true  # Ensure a clean preview branch

      - name: Comment on PR using REST API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -X POST \
               -d "{\"body\": \"📖 **Docs Preview:** [Staging Docs](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)\"}" \
               "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"

  deploy-production:
    needs: build-docs
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Built Docs Artifact
        uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html

      - name: Deploy to GitHub Pages (Production)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Main GitHub Pages branch
          publish_dir: docs/build/html
          keep_files: false  # Overwrite old site
          force_orphan: true  # Ensure a clean gh-pages branch
      - name: Check for Broken Links
        run: |
          pip install linkchecker
          linkchecker https://dtsapetis.github.io/UQpy/

  
