name: Environment and Compatibility Tests

on:
    schedule:
        - cron: '0 0 * * 4'
    workflow_dispatch:

jobs:
    test-matrix:
        name: Run test on multiple OS & Python Versions
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.9', '3.13']
                # os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-cov pytest-split hypothesis pytest-rerunfailures
            - name: Run tests
              run: PYTHONPATH=src pytest --cov=src tests/              
