name: Package & Release

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 

        - name: Install .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.x'

        - name: Install GitVersion as .NET tool
          run: |
            dotnet tool install --global GitVersion.Tool --version 5.*
            dotnet tool list -g
            dotnet-gitversion /version          

        - name: Run GitVersion
          run: |
            dotnet-gitversion /config GitVersion.yml
            VERSION=$(dotnet-gitversion /showvariable MajorMinorPatch)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Use env variable
          run: echo "GitVersion VERSION = $VERSION"

        # - name: Update pyproject.toml with version  
        #   run: |
        #     echo "Replacing version with $VERSION in pyproject.toml"
        #     sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml
        #     cat pyproject.toml
        - name: Set up Python 3.12
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: 'pip'

        - name: Install build tools
          run: python -m pip install --upgrade build twine

        - name: Build package
          run: python -m build -s -v

        - name: Check package validity
          run: twine check dist/*

        - name: Upload package artifact
          uses: actions/upload-artifact@v4
          with:
            name: built-dist
            path: dist/

        
          
