name: Package & Release

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 
        
        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v3.2.1
          with:
            versionSpec: '5.x'
        
        - name: Determine Version
          run: |
           dotnet-gitversion -output json 
        #    -showvariable SemVer > version.json
            
        #   id: versioning_step 
        #   uses: gittools/actions/gitversion/execute@v3.2.1
        #   with:
        #     useConfigFile: true
        #     configFilePath: 'GitVersion.yml'
        
        - name: Display GitVersion variables (without prefix)
          run: |
            echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
            echo "MajorMinorPatch (env.majorMinorPatch)  : ${{ env.majorMinorPatch }}"
            echo "SemVer (env.semVer)                    : ${{ env.semVer }}"
          
