name: Static code analysis

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
  push:
    branches:
      - master 
    paths:
      - 'src/**'
  workflow_dispatch:
permissions:
  security-events: write
  
jobs:
  code-ql-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v2

  sonar-cloud-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # SONAR_HOST_URL: https://sonarcloud.io
  
  code-complexity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4          
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
          python-version: 3.9
    - name: Install Radon
      run: pip instal radon
    - name: Run Radon
      run: |
          radon cc src -a -s -j -o radon-cc-report.json
          radon mi src -a -s -j -o radon-mi-report.json
          radon raw src -j -o radon-raw.json
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: radon-reports
        path: |
          radon-cc-report.json
          radon-mi-report.json
          radon-raw.json
    
  
  
